controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
rutaPrueba:
    path: /rutaPrueba
    controller: App\Controller\ProductController::Prueba